//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MultiplayerSchach {
    
    
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.VisualStudio.Editors.SettingsDesigner.SettingsSingleFileGenerator", "17.10.0.0")]
    internal sealed partial class GuiSettings : global::System.Configuration.ApplicationSettingsBase {
        
        private static GuiSettings defaultInstance = ((GuiSettings)(global::System.Configuration.ApplicationSettingsBase.Synchronized(new GuiSettings())));
        
        public static GuiSettings Default {
            get {
                return defaultInstance;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("1000, 900")]
        public global::System.Drawing.Size FrameSize {
            get {
                return ((global::System.Drawing.Size)(this["FrameSize"]));
            }
            set {
                this["FrameSize"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("asdf")]
        public string asdf {
            get {
                return ((string)(this["asdf"]));
            }
            set {
                this["asdf"] = value;
            }
        }
    }
}
